# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de96d730cc87d6ba8c8283ba815afd139e58c5e0407130506ed784b26b3b388826a6e98e74e7d2e83f977e8f8e1597991877459c4ce5e942f2fa30b20f4c35ad

test:
  secret_key_base: 62e1126eb28b462bed2ab134ab73904dd3533de11e2f31dfdd79ff0092e4f976eb3eac6aa0540a8e56ba71f7690dd5a5e2735caff797eb4c5d60e9256dd110b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
